# TCL File Generated by Component Editor 20.1
# Tue Jun 25 15:00:05 BST 2024
# DO NOT MODIFY


# 
# dijkstra_accel "dijkstra_accel" v1.2
#  2024.06.25.15:00:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dijkstra_accel
# 
set_module_property DESCRIPTION ""
set_module_property NAME dijkstra_accel
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dijkstra_accel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dijkstra_check_step
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dijkstra_check_step.sv SYSTEM_VERILOG PATH dijkstra_accel/dijkstra_check_step.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dijkstra_check_step
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file dijkstra_check_step.sv SYSTEM_VERILOG PATH dijkstra_accel/dijkstra_check_step.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 nios_custom_instruction end
set_interface_property s1 clockCycle 0
set_interface_property s1 operands 2
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 dataa dataa Input 32
add_interface_port s1 datab datab Input 32
add_interface_port s1 clk_en clk_en Input 1
add_interface_port s1 start start Input 1
add_interface_port s1 done done Output 1
add_interface_port s1 result result Output 32
add_interface_port s1 reset reset Input 1
add_interface_port s1 clk clk Input 1

