# TCL File Generated by Component Editor 20.1
# Wed Jun 26 11:26:32 BST 2024
# DO NOT MODIFY


# 
# hw_dijkstra "hw_dijkstra" v1.1
#  2024.06.26.11:26:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hw_dijkstra
# 
set_module_property DESCRIPTION ""
set_module_property NAME hw_dijkstra
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hw_dijkstra
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DijkstraInterface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file constants.v VERILOG PATH ../hardware/Dijkstra/hdl/constants.v
add_fileset_file dijkstra_interface.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/dijkstra_interface.sv TOP_LEVEL_FILE
add_fileset_file dijkstra_top.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/dijkstra_top.sv
add_fileset_file edge_cache.v VERILOG PATH ../hardware/Dijkstra/hdl/edge_cache.v
add_fileset_file edge_cache_mem.v VERILOG PATH ../hardware/Dijkstra/hdl/edge_cache_mem.v
add_fileset_file minheap.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/minheap.sv
add_fileset_file priority_queue.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/priority_queue.sv
add_fileset_file fp_adder.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/math/fp_adder.sv
add_fileset_file fp_comparator.sv SYSTEM_VERILOG PATH ../hardware/Dijkstra/hdl/math/fp_comparator.sv


# 
# parameters
# 
add_parameter MAX_NODES INTEGER 128
set_parameter_property MAX_NODES DEFAULT_VALUE 128
set_parameter_property MAX_NODES DISPLAY_NAME MAX_NODES
set_parameter_property MAX_NODES TYPE INTEGER
set_parameter_property MAX_NODES UNITS None
set_parameter_property MAX_NODES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_NODES HDL_PARAMETER true
add_parameter INDEX_WIDTH INTEGER 7
set_parameter_property INDEX_WIDTH DEFAULT_VALUE 7
set_parameter_property INDEX_WIDTH DISPLAY_NAME INDEX_WIDTH
set_parameter_property INDEX_WIDTH TYPE INTEGER
set_parameter_property INDEX_WIDTH UNITS None
set_parameter_property INDEX_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INDEX_WIDTH HDL_PARAMETER true
add_parameter VALUE_WIDTH INTEGER 32
set_parameter_property VALUE_WIDTH DEFAULT_VALUE 32
set_parameter_property VALUE_WIDTH DISPLAY_NAME VALUE_WIDTH
set_parameter_property VALUE_WIDTH TYPE INTEGER
set_parameter_property VALUE_WIDTH UNITS None
set_parameter_property VALUE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VALUE_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_sink reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input 16
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_readdata readdata Output 32
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave clock_enable clk_en Input 1
add_interface_port nios_custom_instruction_slave select_n n Input 4
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave ready done Output 1
add_interface_port nios_custom_instruction_slave clock clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender interrupt_sender_irq irq Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_sink clk Input 1

